### ISSUE TITLE
writer.addField  changed field value's type to string 

### ISSUE THREAD

**Issue by lovingyu** [ashishdoneriya/influxdb-java#10]
hello, sorry for my poor english

when i use writer.addField  to add a float value , i found in influxdb the field's fieldtype is a string not a float.

the code like this:
 #define param
 float cpu_idle=new Float(vm_info[7]);
 float cpu_wait=new Float(vm_info[8]);
#write param
 writer.addField("cpu_idle", cpu_idle);
 writer.addField("cpu_wait", cpu_wait);

when it's done, in influxdb you can see the fieldtypes.
show field keys:
fieldKey   fieldType
cpu_idle   string
cpu_wait   string

is not a float . 
can u fix it? thank u.

**Comment by ashishdoneriya** [comment]
Hi @lovingyu 
I'll try to fix the problem by today

**Comment by ashishdoneriya** [comment]
Fixed bug, take the latest release 3.0.1
