### ISSUE TITLE
DataWriter.writeData() should check the return status of httpClient.execute()

### ISSUE THREAD

**Issue by keachi** [ashishdoneriya/influxdb-java#4]
Hi

The `DataWriter.writeData()` method does not check the status message of `httpClient.execute(httpPost)`. If the InfluxDB server give a return value HTTP/1.1 400 Bad Request, this can't be detected.

I got this error with InfluxDB v0.13.0 with the following code:

``` Java
Configuration dbConfig = new Configuration(...);
try {
    writer = new DataWriter(dbConfig);
    writer.setTimeUnit(TimeUnit.SECONDS);
    writer.setTime(System.currentTimeMillis() / 1000);

    /* use table player */
    writer.setTableName("servers");

    /* add some data */
    writer.addField("server", "www.example.org");
    writer.addField("value", "100");

    /* write the data to the server */
    writer.writeData();
} catch (Exception error) {
}
```

The return value of writer.writeData().httpClient.execute(httpPost) (Line 69) is the following:

```
[com.db.influxdb.DataWriter:writeData:68]: HTTP/1.1 400 Bad Request [Content-Type: application/json, Request-Id: 0767455a-4d2a-11e6-88e9-000000000000, X-Influxdb-Version: 0.13.0, Date: Mon, 18 Jul 2016 20:55:58 GMT]
```

But to get this error message, I had to change the DataWriter class, so a exception or a return value would be nice.

**Comment by ashishdoneriya** [comment]
Fixed. Now it will throw exception if status code is not 204 (success)

**Comment by ashishdoneriya** [comment]
@2-B If you are writing integer values then don't use double quotes.
eg.
<code>writer.addField("value", "100");</code>
It will assume 100 as a string and will save as a string and you will be not be able to use aggregate functions on this field later (on strings we can't use aggregate functions).
Therefore the correct syntex for writing numbers is <code>writer.addField("value", 100);</code>
