### ISSUE TITLE
Drop Measurement

### ISSUE THREAD

**Issue by alleraro** [ashishdoneriya/influxdb-java#8]
You could implement the DROP and DELETE measurements option????

These options would be great !!!!!

By the way a great job.

**Comment by ashishdoneriya** [comment]
Already Implemented

utilities.dropMeasurement(configuration, measurementname)

**Comment by alleraro** [comment]
Thanks, I had not seen that method.

Now my project is perfect.

Regards and once again thank you!!!!!
